# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: IfNotPresent
  secrets:
    - name: gitlab-registry
podAnnotations: {}
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
  database_url:
  environments:
    - name: APP_NAME
      value: "Единство"
    - name: VKONTAKTE_KEY
      value: "7500406"
    - name: VKONTAKTE_SECRET
      value: "kUdEtA1qyBB1wrBz24uO"
    - name: VKONTAKTE_REDIRECT_URI
      value: "https://leadersofdigital-backend.server.bonch.dev/provider/vkontakte/callback"
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
gitlab:
  app:
  env:
  envName:
  envURL:
service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url: http://my.host.com/
  additionalHosts:
  commonName:
  externalPort: 5000
  internalPort: 5000
ingress:
  tls:
    enabled: true
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  modSecurity:
    enabled: false
    secRuleEngine: "DetectionOnly"
livenessProbe:
  path: "/"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
readinessProbe:
  path: "/"
  initialDelaySeconds: 15
  timeoutSeconds: 35
  scheme: "HTTP"
postgresql:
  enabled: true
  managed: false
  persistence:
    enabled: false
redis:
  enabled: false
  nameOverride: "redis"
  cluster:
    enabled: false
    slaveCount: 0
prometheus:
  metrics: false
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
  requests:
#    cpu: 100m
#    memory: 128Mi
pvc:
  enabled: false
  size: 15Gi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1

workers:
  # worker:
  #   replicaCount: 1
  #   terminationGracePeriodSeconds: 60
  #   command:
  #   - /bin/herokuish
  #   - procfile
  #   - start
  #   - worker
  #   preStopCommand:
  #   - /bin/herokuish
  #   - procfile
  #   - start
  #   - stop_worker
