GET http://localhost:8000/api/users/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|nXnKakAw38G1I4SKR2yS1jwcO8iEF4IjqQbnpgfL4heDvIQVjTiym5XtmimRiup9FtbcqPtiOt9gd3c9

{}

###
